apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-workers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinema-workers
  template:
    metadata:
      labels:
        app: cinema-workers
    spec:
      containers:
        - image: myfirstmolly/workerservice
          name: cinema-workers
          ports:
            - containerPort: 8085
              name: cinema-workers
          env:
            - name: POSTGRES_ENDPOINT
              value: "jdbc:postgresql://192.168.0.101:5432/"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_USERNAME
              value: "postgres"